config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :websites
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/website.rb
class Website < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @websites = Website.all
  end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :set_website, only: %i[ show edit update destroy ]

  # GET /websites or /websites.json
  def index
    @websites = Website.all
  end

  # GET /websites/1 or /websites/1.json
  def show
  end

  # GET /websites/new
  def new
    @website = Website.new
  end

  # GET /websites/1/edit
  def edit
  end

  # POST /websites or /websites.json
  def create
    @website = Website.new(website_params)

    respond_to do |format|
      if @website.save
        format.html { redirect_to website_url(@website), notice: "Website was successfully created." }
        format.json { render :show, status: :created, location: @website }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /websites/1 or /websites/1.json
  def update
    respond_to do |format|
      if @website.update(website_params)
        format.html { redirect_to website_url(@website), notice: "Website was successfully updated." }
        format.json { render :show, status: :ok, location: @website }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /websites/1 or /websites/1.json
  def destroy
    @website.destroy

    respond_to do |format|
      format.html { redirect_to websites_url, notice: "Website was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_website
      @website = Website.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def website_params
      params.require(:website).permit(:title, :url, :img, :desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/home/index.html.erb
<div class="container-fluid">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">NavBar</a>
    <a class="btn btn-success" href="https://github.com/GenericOctopus?tab=repositories" target="_blank">
      Github Repos
    </a>
  </nav>
</div>

<div class="container">
  <div class="row">
    <% @websites.each do |website| %>
      <div class="col-md-4">
        <div class="card">
          <a href="<%=website.url%>" target="_blank"><img src="<%=website.img%>" class="card-img-top" alt="..."></a>
          <div class="card-body">
            <h5 class="card-title"><%=website.title%></h5>
            <p class="card-text">
              <%=website.desc%>
            </p>
            <a href="<%=website.url%>" class="btn btn-primary"><%=website.title%></a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/websites/_form.html.erb
<%= form_with(model: website) do |form| %>
  <% if website.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(website.errors.count, "error") %> prohibited this website from being saved:</h2>

      <ul>
        <% website.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.label :img, style: "display: block" %>
    <%= form.text_field :img %>
  </div>

  <div>
    <%= form.label :desc, style: "display: block" %>
    <%= form.text_area :desc %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/websites/_website.html.erb
<div id="<%= dom_id website %>">
  <p>
    <strong>Title:</strong>
    <%= website.title %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= website.url %>
  </p>

  <p>
    <strong>Img:</strong>
    <%= website.img %>
  </p>

  <p>
    <strong>Desc:</strong>
    <%= website.desc %>
  </p>

</div>

app/views/websites/edit.html.erb
<h1>Editing website</h1>

<%= render "form", website: @website %>

<br>

<div>
  <%= link_to "Show this website", @website %> |
  <%= link_to "Back to websites", websites_path %>
</div>

app/views/websites/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Websites</h1>

<div id="websites">
  <% @websites.each do |website| %>
    <%= render website %>
    <p>
      <%= link_to "Show this website", website %>
    </p>
  <% end %>
</div>

<%= link_to "New website", new_website_path %>

app/views/websites/new.html.erb
<h1>New website</h1>

<%= render "form", website: @website %>

<br>

<div>
  <%= link_to "Back to websites", websites_path %>
</div>

app/views/websites/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @website %>

<div>
  <%= link_to "Edit this website", edit_website_path(@website) %> |
  <%= link_to "Back to websites", websites_path %>

  <%= button_to "Destroy this website", @website, method: :delete %>
</div>